# Application
spring.application.name=fitmecentermanagement
server.port=8080

# Database SQL Server
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=fitnessdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=240305 // thay pass của mỗi người or k 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+7

# Logging
logging.level.com.example.fitmecenter=DEBUG
logging.level.org.springframework.web=DEBUG